[project]
name = "tuican"
version = "0.1.0"
description = "telegram ui components to build app alike bots"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.1",
    "python-telegram-bot>=22.4",
]
